-- Code Consulting Studio — first-party analytics
--
-- Stores selected analytics events generated by the CCS application.
-- The raw event table is not exposed directly to public or authenticated
-- users. Events are written by trusted server-side code only.
--
-- Editors and admins can read aggregated Insights performance data through
-- dedicated database functions instead of querying raw analytics rows.


-- ============================================================
-- 1. Analytics event log
-- ============================================================

create table if not exists public.analytics_events (
  id uuid primary key default gen_random_uuid(),

  name text not null,

  -- Event-specific information such as article slug, locale or CTA
  -- location is stored as a JSON object.

  properties jsonb not null default '{}'::jsonb,

  occurred_at timestamptz not null default now()
);


-- Speeds up queries that filter by event name and recent date.

create index if not exists analytics_events_name_occurred_idx
  on public.analytics_events (
    name,
    occurred_at desc
  );


-- ============================================================
-- 2. Row Level Security
-- ============================================================
--
-- There are intentionally no anon or authenticated policies.
--
-- Public analytics submissions go through the application's protected
-- server-side API, which writes using the privileged Supabase client.
--
-- Editors/admins do not receive direct access to raw analytics rows.
-- They read aggregated information through the RPC functions below.

alter table public.analytics_events
  enable row level security;


-- ============================================================
-- 3. Top Insights articles
-- ============================================================
--
-- Returns article view counts for the selected period.
--
-- SECURITY DEFINER allows the function to read analytics_events even
-- though normal authenticated users cannot query that table directly.
--
-- Access is still restricted to active editors and admins.

create or replace function public.insights_top_articles(
  days_back int default 30,
  result_limit int default 10
)
returns table (
  slug text,
  locale text,
  view_count bigint
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  safe_days_back int;
  safe_result_limit int;
begin

  if not public.is_active_editor_or_admin() then
    raise exception 'not authorized';
  end if;

  -- Keep analytics queries within reasonable limits.
  safe_days_back := greatest(1, least(days_back, 3650));
  safe_result_limit := greatest(1, least(result_limit, 100));

  return query
    select
      ae.properties->>'slug' as slug,
      ae.properties->>'locale' as locale,
      count(*) as view_count
    from public.analytics_events ae
    where ae.name = 'article_view'
      and ae.occurred_at >= now() - make_interval(days => safe_days_back)
      and ae.properties->>'slug' is not null
    group by
      ae.properties->>'slug',
      ae.properties->>'locale'
    order by view_count desc
    limit safe_result_limit;

end;
$$;


-- Do not allow every PostgreSQL role to execute the function.

revoke all
  on function public.insights_top_articles(int, int)
  from public;


-- Only signed-in users can call the RPC.
-- The function itself then checks whether the user is an active
-- editor or admin.

grant execute
  on function public.insights_top_articles(int, int)
  to authenticated;

grant execute
  on function public.insights_top_articles(int, int)
  to service_role;


-- ============================================================
-- 4. Insights CTA click counts
-- ============================================================
--
-- Returns CTA click totals grouped by article and CTA location.

create or replace function public.insights_cta_click_counts(
  days_back int default 30
)
returns table (
  slug text,
  cta_location text,
  click_count bigint
)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  safe_days_back int;
begin

  if not public.is_active_editor_or_admin() then
    raise exception 'not authorized';
  end if;

  safe_days_back := greatest(1, least(days_back, 3650));

  return query
    select
      ae.properties->>'slug' as slug,
      ae.properties->>'cta_location' as cta_location,
      count(*) as click_count
    from public.analytics_events ae
    where ae.name = 'article_cta_click'
      and ae.occurred_at >= now() - make_interval(days => safe_days_back)
      and ae.properties->>'slug' is not null
    group by
      ae.properties->>'slug',
      ae.properties->>'cta_location'
    order by click_count desc;

end;
$$;


revoke all
  on function public.insights_cta_click_counts(int)
  from public;

grant execute
  on function public.insights_cta_click_counts(int)
  to authenticated;

grant execute
  on function public.insights_cta_click_counts(int)
  to service_role;


-- ============================================================
-- 5. Data API privileges
-- ============================================================
--
-- This project was created with automatic table exposure disabled.
--
-- Raw analytics data remains unavailable to anon/authenticated roles.
-- Only trusted server-side code receives direct table access.

grant all
  on table public.analytics_events
  to service_role;